# -*- coding: utf-8 -*-
"""E-commerce_Sales_Data_Analysis_using_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100tXNsxVJCXrgA9kDgtTLBSfe4JMScIP

# **Tasks**

1. Calculate the monthly sales of the store and identify which month had the
highest sales and which month had the lowest sales.
2. Analyze sales based on product categories and determine which category has
the lowest sales and which category has the highest sales.
3. The sales analysis needs to be done based on sub-categories
4. Analyze the monthly profit from sales and determine which month had the highest profit.
5. Analyze the profit by category and sub-category.
6. Analyze the sales and profit by customer segment
7. Analyze the sales to profit ratio
"""

from google.colab import drive
drive.mount('/content/Myfiles')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data= pd.read_csv('/content/Myfiles/MyDrive/Sample - Superstore.csv', encoding='latin1')
data.head()

data.shape

data.describe()

data.info()

"""# **Converting date columns**"""

data['Order Date'] = pd.to_datetime(data['Order Date'])

data['Ship Date'] = pd.to_datetime(data['Ship Date'])

data.head(1)

data['Order Month'] = data['Order Date'].dt.month
data['Order Year'] = data['Order Date'].dt.year
data['Order Day of Week'] = data['Order Date'].dt.dayofweek

data.head(1)

"""# **Monthly sales Analysis**"""

x = data.groupby('Order Month')['Sales'].groups.keys()
y = data.groupby('Order Month')['Sales'].sum().values

plt.xlabel('Order Month')
plt.ylabel('Sales')
plt.title('Monthly Sales Analysis')
plot = plt.plot(x,y)
plt.show()

"""# **Sales by Category**"""

sales_by_category = data.groupby('Category')['Sales'].sum().reset_index()

sales_by_category

x = data.groupby('Category')['Sales'].sum().index
y = data.groupby('Category')['Sales'].sum().values

plt.bar(x,y)
plt.xlabel('Category')
plt.ylabel('Sales')
plt.show()

"""# **Sales analysis by Sub Category**"""

data.head(1)

sales_by_subcategory= data.groupby('Sub-Category')['Sales'].sum()

sales_by_subcategory

x = data.groupby('Sub-Category')['Sales'].sum().index
y = data.groupby('Sub-Category')['Sales'].sum().values

plt.bar(x,y)
plt.xticks(rotation='vertical')
plt.xlabel('Sub-Category')
plt.ylabel('Sales')
plt.show()

#fig = px.bar(sales_by_subcategory,
#            y='Sales',
#             title='Sales Analysis bu Sub- Category')
#fig.show()

"""# **Monthly Profit Analysis**"""

profit_by_month= data.groupby('Order Month')['Profit'].sum().reset_index()

profit_by_month

x = data.groupby('Order Month')['Profit'].groups.keys()
y = data.groupby('Order Month')['Profit'].sum().values

plt.xlabel('Order Month')
plt.ylabel('Profit')
plt.title('Monthly Profit Analysis')
plot = plt.plot(x,y)
plt.show()




#fig = px.line(profit_by_month,
#              x='Order Month',
#              y='Profit',
#             title='Monthly Profit Analysis')

#fig.show()

"""# **Profit by Category**"""

profit_by_category = data.groupby('Category')['Profit'].sum()

profit_by_category

data.groupby('Category')['Profit'].sum().plot(kind='pie',autopct='%1.1f%%')
plt.show()

"""# **Profit by Subcategory**"""

profit_by_subcategory = data.groupby('Sub-Category')['Profit'].sum()

profit_by_subcategory

data.groupby('Sub-Category')['Profit'].sum().plot(kind='bar')
plt.show()



"""# **Sals and Profit - Customer Segment**"""

data.head()

segment_analysis = data.groupby('Segment')[['Profit','Sales']].sum()
fig,ax1 = plt.subplots(figsize=(10,5))
ax2 = ax1.twinx()

ax1.bar(segment_analysis.index,segment_analysis['Sales'],color='b',label='Sales')
ax2.plot(segment_analysis.index,segment_analysis['Profit'],color='r',label='Profit')


ax1.set_xlabel('Customer Segment')
ax1.set_ylabel('Sales',color='b')
ax2.set_ylabel('Profit',color='r')
plt.title('Sales and Profit by Customer Segment')
plt.show()

"""# **Sales to Profit Ratio**"""

sales_profit_by_segment = data.groupby('Segment')[['Profit','Sales']].sum()
sales_profit_by_segment['Sales to Profit Ratio'] = sales_profit_by_segment['Sales']/sales_profit_by_segment['Profit']
print(sales_profit_by_segment)

"""**Conclusion**

1.Lowest sale is in November month AND Highest sale is in Janeuary month.

2.Highest Sale Category:

1.   Technology
2.   Furniture
3.   Office Supplies

3.Phone is Highest sale in sub-category.

4.Highest profit is in Dec AND Lowest profit is in Janeuary.

5.Technology is the highest sale in Category AND Coppiers is the highest sale in sub-categories.

6.Consumer is the highest sale, Second was corporate customer segment and third was home office.

7.Sales to Profit Ratio is 8.65
"""

